/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class srv_work_PVlib */

#ifndef _Included_srv_work_PVlib
#define _Included_srv_work_PVlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     srv_work_PVlib
 * Method:    lib_getPic
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_srv_1work_PVlib_lib_1getPic
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     srv_work_PVlib
 * Method:    lib_getVoi
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_srv_1work_PVlib_lib_1getVoi
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif

